# Generated by Django 4.1.2 on 2022-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_section',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='featured_agents_section',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='newsletter_section',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='recent_property_section',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='reviews_section',
            name='repeatfields_ptr',
        ),
        migrations.RemoveField(
            model_name='teams_meet_section',
            name='repeatfields_ptr',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Contact_section',
        ),
        migrations.DeleteModel(
            name='Featured_Agents_Section',
        ),
        migrations.DeleteModel(
            name='Newsletter_Section',
        ),
        migrations.DeleteModel(
            name='Newsletters',
        ),
        migrations.DeleteModel(
            name='Recent_Property_Section',
        ),
        migrations.DeleteModel(
            name='Reviews_Section',
        ),
        migrations.DeleteModel(
            name='Teams_meet_section',
        ),
    ]
