# Generated by Django 4.1.2 on 2022-10-06 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPropertyImage',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('image1', models.ImageField(upload_to='Additional_Images')),
                ('image2', models.ImageField(upload_to='Additional_Images')),
                ('image3', models.ImageField(upload_to='Additional_Images')),
                ('image4', models.ImageField(upload_to='Additional_Images')),
                ('image5', models.ImageField(upload_to='Additional_Images')),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bathrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Garages',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='InactiveProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProperty',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('property_type', models.CharField(max_length=254)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('inactiveproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Property.inactiveproperties')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('FOR SALE', 'For Sale'), ('FOR RENT', 'For Rent')], max_length=150)),
                ('address_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='Property_images')),
                ('bathroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_bathrooms', to='Property.bathrooms')),
                ('bedroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_bedrooms', to='Property.bedrooms')),
                ('garage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_garages', to='Property.garages')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_property', to='Property.typeproperty')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Property.inactiveproperties',),
        ),
    ]
