# Generated by Django 4.1.2 on 2022-10-10 23:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
