# Generated by Django 4.1.2 on 2022-10-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_properties_more_images_alter_properties_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='more_images',
        ),
        migrations.AddField(
            model_name='properties',
            name='additional_image1',
            field=models.ImageField(blank=True, upload_to='Additional_Images'),
        ),
        migrations.AddField(
            model_name='properties',
            name='additional_image2',
            field=models.ImageField(blank=True, upload_to='Additional_Images'),
        ),
        migrations.AddField(
            model_name='properties',
            name='additional_image3',
            field=models.ImageField(blank=True, upload_to='Additional_Images'),
        ),
        migrations.AddField(
            model_name='properties',
            name='additional_image4',
            field=models.ImageField(blank=True, upload_to='Additional_Images'),
        ),
        migrations.AddField(
            model_name='properties',
            name='additional_image5',
            field=models.ImageField(blank=True, upload_to='Additional_Images'),
        ),
        migrations.DeleteModel(
            name='AdditionalPropertyImage',
        ),
    ]
