# Generated by Django 4.1.2 on 2022-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Property', '0005_remove_properties_additional_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('city', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_cities', to='Property.cities'),
        ),
    ]
