# Generated by Django 4.1.2 on 2022-10-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_requesttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttime',
            name='save_user',
        ),
    ]
