# Generated by Django 4.1.2 on 2022-10-13 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Property', '0008_remove_requesttime_save_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttime',
            name='save_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
