# Generated by Django 4.1.2 on 2022-10-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_requesttime_save_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='address_name',
        ),
    ]
